apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eks-lambda-role-binding
  namespace: test-eks-lambda
subjects:
- kind: Group
  name: eks-lambda
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: eks-lambda-role
  apiGroup: rbac.authorization.k8s.io